language: minimal # setting language to C will override cross-compiler and fail

compiler:
  - gcc
  - clang

sudo: required
dist: trusty

notifications:
  irc:
    channels:
      - "irc://irc.freenode.net:8001/#zjs"
    on_success: change
    on_failure: always

env:
  global:
    - ZEPHYR_GCC_VARIANT=zephyr
    - ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
    - ZEPHYR_BASE=$TRAVIS_BUILD_DIR/deps/zephyr
    - ZEPHYR_SDK_VERSION=0.9.2
    - ZEPHYR_SDK_DOWNLOAD_FOLDER=https://github.com/zephyrproject-rtos/meta-zephyr-sdk/releases/download/$ZEPHYR_SDK_VERSION
    - ZEPHYR_SDK_SETUP_BINARY=zephyr-sdk-$ZEPHYR_SDK_VERSION-setup.run
    - ZEPHYR_SDK_DOWNLOAD_URL=$ZEPHYR_SDK_DOWNLOAD_FOLDER/$ZEPHYR_SDK_SETUP_BINARY
    - CMAKE_SHORTVER=3.9
    - CMAKE_VERSION=3.9.5
matrix:
  fast_finish: true
  include:
    - os: linux
      env: TARGET="zephyr"
    - os: linux
      env: TARGET="extra"
    - os: linux
      env: TARGET="linux"
    - os: linux
      dist: trusty
      env: TARGET="ashell"
    - os: osx
      osx_image: xcode9.1
      env: TARGET="linux"
  allow_failures:
    - os: osx

cache:
  directories:
    - $ZEPHYR_SDK_INSTALL_DIR
    - /usr/local/bin

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update -qq &&
      sudo apt-get install libc6-dev-i386 make gperf gcc g++ python3-ply python3-yaml python3-pip device-tree-compiler ncurses-dev uglifyjs -qq &&
      sudo pip3 install pyelftools &&
      sudo apt-get purge cmake;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && (! $(which cmake) -o "$(cmake --version | head -1)" != "cmake version $CMAKE_VERSION") ]]; then
      wget https://cmake.org/files/v$CMAKE_SHORTVER/cmake-$CMAKE_VERSION.tar.gz &&
      tar xf cmake-$CMAKE_VERSION.tar.gz &&
      cd cmake-$CMAKE_VERSION &&
      ./bootstrap &&
      make -j4 &> /dev/null &&
      sudo make install &&
      cd ..;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update &&
      brew install python3 &&
      sudo pip3 install pyelftools;
    fi

install: >
  if [[ "$TARGET" != "linux" && "$(cat $ZEPHYR_SDK_INSTALL_DIR/sdk_version)" != "$ZEPHYR_SDK_VERSION" ]; then
    wget $ZEPHYR_SDK_DOWNLOAD_URL &&
    chmod +x $ZEPHYR_SDK_SETUP_BINARY &&
    rm -rf $ZEPHYR_SDK_INSTALL_DIR &&
    ./$ZEPHYR_SDK_SETUP_BINARY --quiet -- -y -d $ZEPHYR_SDK_INSTALL_DIR > /dev/null;
  fi

before_script: >
  source zjs-env.sh &&
  if [ "$TARGET" != "linux" ]; then
    make update &&
    source deps/zephyr/zephyr-env.sh
  fi

script: >
  trlite -l $TARGET
